export type { Rng, Pt, WeightedPt, PixelBuffer, Rect } from './types';
export { createRng } from './engine/rng';
export { fromText, fromImage, fromShape, fromSVGPath, fromImageData } from './engine/formations';
export { textReveal } from './components/text-reveal';
export type { TextRevealOpts } from './components/text-reveal';
export { sceneMorph } from './components/scene-morph';
export type { SceneMorphOpts } from './components/scene-morph';
export { imageReveal } from './components/image-reveal';
export type { ImageRevealOpts } from './components/image-reveal';
export type { InkStage, MorphOpts, Phase, TiltOpts, ViewParams } from './stage/ink-stage';
export { easedProgress } from './engine/choreography';
export { parseInkAttributes, autoInit } from './auto-init';
export { coverReveal } from './components/cover-reveal';
export type { CoverRevealOpts } from './components/cover-reveal';
export { statReveal, parseStatValue } from './components/stat-reveal';
export type { StatRevealOpts, ParsedStatValue } from './components/stat-reveal';
export { recommendedParticleCount } from './engine/budget';
export { column, fromPoints3d } from './engine/forms3d';
export type { ColumnOpts, Pt3D } from './engine/forms3d';
