export type { Rng, Pt, WeightedPt, PixelBuffer, Rect } from './types';
export { createRng } from './engine/rng';
export { fromText, fromImage } from './engine/formations';
export { textReveal } from './components/text-reveal';
export type { TextRevealOpts } from './components/text-reveal';
export { sceneMorph } from './components/scene-morph';
export type { SceneMorphOpts } from './components/scene-morph';
export { imageReveal } from './components/image-reveal';
export type { ImageRevealOpts } from './components/image-reveal';
export type { InkStage, MorphOpts } from './stage/ink-stage';
export { parseInkAttributes, autoInit } from './auto-init';
